-- Canvas 27 — PostgreSQL / Supabase

CREATE TABLE IF NOT EXISTS public.artists (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    temp_name text NULL,
    email text NOT NULL UNIQUE,
    password_hash text NOT NULL,
    full_name text NULL,
    bio text NULL,
    avatar_url text NULL,
    created_at timestamptz DEFAULT current_timestamp
);

CREATE TABLE IF NOT EXISTS public.photos (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    artist_id bigint NOT NULL,
    title text NULL,
    file_path text NOT NULL,
    latitude text NULL,
    longitude text NULL,
    created_at timestamptz DEFAULT current_timestamp,
    CONSTRAINT fk_photos_artist FOREIGN KEY (artist_id) REFERENCES public.artists(id) ON DELETE CASCADE
);

-- Índice para optimizar búsquedas de fotos por artista
CREATE INDEX IF NOT EXISTS idx_photos_artist ON public.photos (artist_id);